/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login.group.pkg9;

import javax.swing.JOptionPane;
import com.opencsv.CSVReader;
import com.opencsv.CSVWriter;
import static com.opencsv.ICSVWriter.NO_QUOTE_CHARACTER;
import com.opencsv.exceptions.CsvException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.lang.String;

/**
 *
 * @author Shekinah Jabez
 */
public class Login extends javax.swing.JFrame {

    private static final String CSV_FILE = "src/login/group/pkg9/Credentials.csv";
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlBlue = new javax.swing.JPanel();
        jPnllightBlue = new javax.swing.JPanel();
        jLblLogo = new javax.swing.JLabel();
        jLblUname = new javax.swing.JLabel();
        jLblmotorPay = new javax.swing.JLabel();
        jLblPword = new javax.swing.JLabel();
        jUnameField = new javax.swing.JTextField();
        jPwordField = new javax.swing.JPasswordField();
        jBtnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPnlBlue.setBackground(java.awt.SystemColor.activeCaption);

        jPnllightBlue.setBackground(java.awt.SystemColor.inactiveCaption);

        jLblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logo/MotorPH.Logo2.png"))); // NOI18N

        jLblUname.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblUname.setForeground(new java.awt.Color(255, 255, 255));
        jLblUname.setText("Username");

        jLblmotorPay.setFont(new java.awt.Font("Yu Gothic", 1, 24)); // NOI18N
        jLblmotorPay.setForeground(new java.awt.Color(102, 102, 255));
        jLblmotorPay.setText("MOTORPAY");

        jLblPword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblPword.setForeground(java.awt.Color.white);
        jLblPword.setText("Password");

        jUnameField.setForeground(new java.awt.Color(0, 0, 51));
        jUnameField.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        jUnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUnameFieldActionPerformed(evt);
            }
        });

        jPwordField.setForeground(new java.awt.Color(0, 0, 51));
        jPwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPwordFieldActionPerformed(evt);
            }
        });

        jBtnLogin.setText("LOGIN");
        jBtnLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnllightBlueLayout = new javax.swing.GroupLayout(jPnllightBlue);
        jPnllightBlue.setLayout(jPnllightBlueLayout);
        jPnllightBlueLayout.setHorizontalGroup(
            jPnllightBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnllightBlueLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jBtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(284, 284, 284))
            .addGroup(jPnllightBlueLayout.createSequentialGroup()
                .addGroup(jPnllightBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnllightBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPnllightBlueLayout.createSequentialGroup()
                            .addGap(196, 196, 196)
                            .addComponent(jLblUname)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jUnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPnllightBlueLayout.createSequentialGroup()
                            .addGap(270, 270, 270)
                            .addComponent(jLblmotorPay))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnllightBlueLayout.createSequentialGroup()
                            .addGap(196, 196, 196)
                            .addComponent(jLblPword, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPnllightBlueLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPnllightBlueLayout.setVerticalGroup(
            jPnllightBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnllightBlueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPnllightBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnllightBlueLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblmotorPay)
                        .addGap(12, 12, 12)
                        .addComponent(jUnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnllightBlueLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLblUname)
                        .addGap(30, 30, 30)
                        .addGroup(jPnllightBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLblPword)
                            .addComponent(jPwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(55, 55, 55)
                .addComponent(jBtnLogin)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPnlBlueLayout = new javax.swing.GroupLayout(jPnlBlue);
        jPnlBlue.setLayout(jPnlBlueLayout);
        jPnlBlueLayout.setHorizontalGroup(
            jPnlBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBlueLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPnllightBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPnlBlueLayout.setVerticalGroup(
            jPnlBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBlueLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPnllightBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlBlue, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLoginActionPerformed
        String userName = jUnameField.getText();
        //String passWord = new String (jPwordField.getText());
        String passWord = jPwordField.getText();       
        Boolean isValidLogIn = false;
        
        try {
            isValidLogIn = validateLogin(userName, passWord);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
          
        if(!isValidLogIn){
           JOptionPane.showMessageDialog(this, 
                                         "Incorrect Credential.",
                                         "",
                                         JOptionPane.ERROR_MESSAGE);
        }
        else
        {
           JOptionPane.showMessageDialog(this, 
                                         "Log In Successful!!!",
                                         "",
                                         JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_jBtnLoginActionPerformed
    
    private boolean validateLogin(String userName, String passWord) throws IOException{
        
        String line = "";
        CSVReader csvReader = null;
        
        try{             
            csvReader = new CSVReader(new FileReader(new File(CSV_FILE)));                
            List<String[]> allData = csvReader.readAll();                                             
            for(int i=0;i<allData.size();i++){
                String[] valUserName = new String [allData.get(i).length]; 
                valUserName = allData.get(i);                  
                if (valUserName[0].equalsIgnoreCase(userName)){
                    if(valUserName[1].equals(passWord)){
                        return true;}                                            
                }
            }            
        }catch(CsvException e){e.printStackTrace();}           
        finally{csvReader.close();}
        return false;
    }
    
    private void jPwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPwordFieldActionPerformed

    private void jUnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUnameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLogin;
    private javax.swing.JLabel jLblLogo;
    private javax.swing.JLabel jLblPword;
    private javax.swing.JLabel jLblUname;
    private javax.swing.JLabel jLblmotorPay;
    private javax.swing.JPanel jPnlBlue;
    private javax.swing.JPanel jPnllightBlue;
    private javax.swing.JPasswordField jPwordField;
    private javax.swing.JTextField jUnameField;
    // End of variables declaration//GEN-END:variables
}
